#!/bin/sh

install_file="$(mktemp)"
depended_upon_file="$(mktemp)"

# Grab the list of all packages I have installed, sort them, and put them into install file
dpkg -l | grep '^i' | cut -f 3 -d ' ' | sort | uniq > "$install_file"

# Grab the list of all packages that are depended upon, sort them, and put them into depended_upon_file
apt-cache dotty | grep -F -- '->' | cut -d '"' -f4 | sort | uniq > "$depended_upon_file"

# Now use comm to extract only the packages that are installed but not depended upon
comm -23 "$install_file" "$depended_upon_file"

# Then cleanup
rm "$install_file" "$depended_upon_file"
