#!/bin/sh

packages="$(dpkg -l | grep '^i' | cut -f 3 -d ' ' | sort | uniq)"
dotty_file="$(mktemp)"
apt-cache dotty > "$dotty_file"

IFS="
"

unique_depended_on=""

for line in $(cat "$dotty_file"); do
	if [ -z "$(echo "$line" | sed -n '/->/p')" ]; then
		#echo "$line is not an arrow"
		continue;
	fi
	depended_on="$(echo "$line" | sed 's/"[^"]*" -> "\([^"]*\)".*/\1/')"
	unique_depended_on="$(echo -e "${depended_on}\n$unique_depended_on")"
done

rm -f "$dotty_file"

unique_depended_on="$(echo "$unique_depended_on" | sort | uniq)"

intersection="$(echo -n "${unique_depended_on}\n$packages" | sort | uniq -d)"

leaves="$(echo -n "${unique_depended_on}\n$intersection" | sort | uniq -u)"

echo "$leaves"
