#!/bin/sh

packages="$(dpkg -l | grep '^i' | cut -f 3 -d ' ' | sort | uniq)"
dotty_file="$(mktemp)"
apt-cache dotty > "$dotty_file"

IFS="
"

for line in $(cat "$dotty_file"); do
	if [ -z "$(echo "$line" | sed -n '/->/p')" ]; then
		#echo "$line is not an arrow"
		continue;
	fi
	# This should be cut... (Maybe on -d '"' and -f 4...)
	depended_on="$(echo "$line" | sed 's/"[^"]*" -> "\([^"]*\)".*/\1/')"
	# Grep -f
	packages="$(echo "$packages" | sed "/^$depended_on\$/d")"
done

rm -f "$dotty_file"

echo "$packages"
